### ISSUE TITLE
Document OpenSTEF architecture

### ISSUE THREAD

**Issue by Sander3003** [OpenSTEF/openstef#242]
As a (potential) user
I would like to see the OpenSTEF (overview) architecture with all relevant interfaces
So I can see how other systems can interface with OpenSTEF

**Comment by Davidswinkels** [comment]
Hi @Sander3003. Thanks for your comment to request more information. To clarify:
1. Are you interested in the software/data architecture of OpenSTEF package? Plus how the whole system is deployed/orchestrated? So that you can run the whole application yourself potentially?
2. Or are you interested how to get the short term prediction data of energy load from the OpenSTEF application? So you can integrate your own application to retrieve data from OpenSTEF application?

**Comment by Sander3003** [comment]
An overview architecture like this would be a nice: https://fledge-iot.readthedocs.io/en/latest/fledge_architecture.html; A basic description of the components and interfaces. It helps to see how OpenSTEF can fit into architectures.

**Comment by Davidswinkels** [comment]
Thanks for the clear example. We should have some documentation like that and will check what we can add soon :)

**Comment by Sander3003** [comment]
Do you have a URL to the documentation? It is unclear to me where to find it.
